"""added category images

Revision ID: 8220409c1d91
Revises: 8052e49fd032
Create Date: 2021-10-15 11:07:22.121173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8220409c1d91'
down_revision = '8052e49fd032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'image')
    # ### end Alembic commands ###
