"""added image to item model

Revision ID: f6c4c1326347
Revises: 8220409c1d91
Create Date: 2021-10-15 13:09:10.615192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c4c1326347'
down_revision = '8220409c1d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'image')
    # ### end Alembic commands ###
